#!/bin/bash
#
# A profile may or may not have this file.
# If it exists, it runs after "sysroot" is mounted.

[[ -v installbase ]] || source /var/tmp/install/common.sh

copy_lukskey() {
  [[ -f $installbase/lukskey ]] || return
  mkdir -p $sysroot$installbase
  cp $installbase/lukskey $sysroot$installbase
}

postmount() {
  run copy_lukskey || return
}

return 2> /dev/null || {
  postmount
}
