#!/bin/bash

[[ -v installbase ]] || source /var/tmp/install/common.sh

copy_lukskey() {
  [[ -f $installbase/lukskey ]] || return
  mkdir -p $sysroot$installbase
  cp $installbase/lukskey $sysroot$installbase
}

postmount() {
  run copy_lukskey || return
}

return 2> /dev/null || {
  postmount
}
