#!/bin/bash
#
# This runs very early. Before preinstall.
# Its job is to make sure that the partitions named in the profile config exist,
# are formatted and labeled, but not mounted yet.

[[ -v installbase ]] || source /var/tmp/install/common.sh

get_pvrootsize() {
  local disksize efisize=2044
  disksize=$(get_disksize)
  echo $(( disksize - efisize - 32 ))
}

print_parted_commands() {
  local efisize=2044
  local pvrootsize=$(get_pvrootsize)
  local pos=4
  echo "mklabel gpt"
  echo "mkpart EFISYS fat32 ${pos}MiB $(( pos + efisize ))MiB"
  (( pos += efisize ))
  echo "set 1 esp on"
  echo "mkpart pvroot ext4 ${pos}MiB $(( pos + pvrootsize ))MiB"
  (( pos += pvrootsize ))
}

ask_new_lukskey() {
  local reply0 reply1
  read -rsp "Choose lukskey: " reply0
  echo
  (( ${#reply0} >= 8 )) || return $(error "minimum 8 characters")
  [[ $reply0 = "${reply0// /}" ]] || return $(error "spaces not allowed")
  read -rsp "Confirm lukskey: " reply1
  echo
  [[ $reply0 = "$reply1" ]] || return $(error "no match")
  echo -n "$reply0" > $installbase/lukskey
  chmod 600 $installbase/lukskey
}

create_partitions() {
  local disk part pvroot luksroot rootsize homesize label_home label_root label_efi
  local pvrootsize=$(get_pvrootsize)
  label_home=$(get_config .storage.luks_lvm.partition.home) || return
  label_root=$(get_config .storage.luks_lvm.partition.root) || return
  label_efi=$(get_config .storage.luks_lvm.partition.efi) || return
  [[ $label_home = luks-* ]] || return $(error "invalid label: $label_home")
  [[ $label_root = luks-* ]] || return $(error "invalid label: $label_root")
  while :; do
    ask_new_lukskey && break
  done
  disk=$(get_disk) || return $(error "get_disk")
  parted --script --align optimal $disk -- $(print_parted_commands) || return 
  mkfs.vfat -n $label_efi -F 32 $(by_partlabel EFISYS) || return
  pvroot=$(by_partlabel pvroot)
  cryptsetup luksFormat --force-password --batch-mode $pvroot $installbase/lukskey || return
  cryptsetup luksOpen --batch-mode --key-file=$installbase/lukskey $pvroot luks || return
  cryptsetup config $pvroot --label pvroot || return
  luksroot=$(get_only_child $pvroot) || return
  pvcreate $luksroot || return
  vgcreate luks $luksroot || return
  rootsize=$(( pvrootsize / 2 ))
  rootsize=$(( rootsize > 65536 ? 65536 : rootsize ))
  rootsize=$(( rootsize < 8192 ? 8192 : rootsize ))
  homesize=$(( pvrootsize - rootsize - 32 ))
  homesize=$(( homesize > 65536 ? 65536 : homesize ))
  lvcreate -L ${rootsize}M -n ${label_root#luks-} luks || return
  lvcreate -L ${homesize}M -n ${label_home#luks-} luks || return
  mkfs.ext4 -q -L $label_root /dev/mapper/$label_root <<< y || return
  mkfs.ext4 -q -L $label_home /dev/mapper/$label_home <<< y || return
}

ask_existing_lukskey() {
  local REPLY pvroot
  pvroot=$(blkid --label pvroot 2> /dev/null) || return 1
  echo "Found pvroot: $pvroot"
  read -rsp "Enter lukskey, or leave empty to wipe: "
  echo
  if [[ -z $REPLY ]]; then
    echo -n "" > $installbase/lukskey
    return 1
  fi
  echo -n "$REPLY" > $installbase/lukskey
  chmod 600 $installbase/lukskey
  cryptsetup luksOpen -q --disable-external-tokens --key-file $installbase/lukskey --test-passphrase $pvroot
}

unlock() {
  [[ -f $installbase/lukskey ]] || return 1
  local pvroot luks_root efisys label_home label_root label_efi
  label_home=$(get_config .storage.luks_lvm.partition.home) || return
  label_root=$(get_config .storage.luks_lvm.partition.root) || return
  label_efi=$(get_config .storage.luks_lvm.partition.efi) || return
  [[ $label_home = luks-* ]] || return $(error "invalid label: $label_home")
  [[ $label_root = luks-* ]] || return $(error "invalid label: $label_root")
  efisys=$(blkid --label $label_efi) || return
  pvroot=$(blkid --label pvroot 2> /dev/null) || return
  cryptsetup luksOpen -q --disable-external-tokens --key-file $installbase/lukskey $pvroot luks || return
  vgchange -ay
  luksroot=$(blkid --label $label_root) || return
  blkid --label $label_home || return
  mkfs.ext4 -q -L $label_root $luksroot <<< y || return
  mkfs.vfat -n $label_efi -F 32 $efisys || return
}

wipe() {
  local REPLY
  while :; do
    read -rp "Erase all data on $(get_disk)? [y/N] "
    if [[ $REPLY =~ [yY] ]]; then
      break
    elif [[ $REPLY =~ [nN] ]]; then
      echo "Installation halted."
      sleep inf
    fi
  done
  create_partitions
}

prepare_partitions() {
  if ! blkid --label pvroot &> /dev/null; then
    echo "No such partition: pvroot"
    wipe
    return
  fi
  while :; do
    if ask_existing_lukskey; then
      unlock
      return
    elif is_empty_file $installbase/lukskey; then
      wipe
      return
    fi
  done
}

return 2> /dev/null || {
  prepare_partitions
}
