#!/bin/bash
#
# This runs very early.
# Its job is to make sure that the partitions named in the profile config exist,
# are formatted and labeled, but not mounted yet.

[[ -v installbase ]] || source /var/tmp/install/common.sh

get_pvrootsize() {
  local efisize=2044 disksize
  disksize=$(get_disksize)
  echo $(( disksize - efisize - 32 ))
}

print_parted_commands() {
  local efisize=2044 pos=4 pvrootsize pvname
  pvrootsize=$(get_pvrootsize)
  pvname=$(get_config .storage.luks_lvm.pvname)
  echo "mklabel gpt"
  echo "mkpart EFISYS fat32 ${pos}MiB $(( pos + efisize ))MiB"
  (( pos += efisize ))
  echo "set 1 esp on"
  echo "mkpart $pvname ext4 ${pos}MiB $(( pos + pvrootsize ))MiB"
  (( pos += pvrootsize ))
}

ask_new_lukskey() {
  local reply0 reply1
  read -rsp "Choose lukskey: " reply0
  echo
  (( ${#reply0} >= 8 )) || {
    echo "ERROR: minimum 8 characters"
    return 1
  }
  [[ $reply0 = "${reply0// /}" ]] || {
    echo "ERROR: spaces not allowed"
    return 1
  }
  read -rsp "Confirm lukskey: " reply1
  echo
  [[ $reply0 = "$reply1" ]] || {
    echo "ERROR: no match"
    return 1
  }
  echo -n "$reply0" > $installbase/lukskey
  chmod 600 $installbase/lukskey
}

create_partitions() {
  local disk pvroot pvrootsize luksroot rootsize homesize optsize label_home label_opt label_root label_efi pvname vgname
  pvrootsize=$(get_pvrootsize)
  pvname=$(get_config .storage.luks_lvm.pvname) || return
  vgname=$(get_config .storage.luks_lvm.vgname) || return
  label_home=$(get_config .storage.luks_lvm.partition.home) || return
  label_opt=$(get_config .storage.luks_lvm.partition.opt) || return
  label_root=$(get_config .storage.luks_lvm.partition.root) || return
  label_efi=$(get_config .storage.luks_lvm.partition.efi) || return
  while :; do
    ask_new_lukskey && break
  done
  disk=$(get_disk) || return
  parted --script --align optimal $disk -- $(print_parted_commands) || return 
  mkfs.vfat -n $label_efi -F 32 $(by_partlabel EFISYS) || return
  pvroot=$(by_partlabel $pvname)
  cryptsetup luksFormat --force-password --batch-mode $pvroot $installbase/lukskey || return
  cryptsetup luksOpen --batch-mode --key-file=$installbase/lukskey $pvroot $vgname || return
  cryptsetup config $pvroot --label $pvname || return
  luksroot=$(get_only_child $pvroot) || return
  pvcreate $luksroot || return
  vgcreate $vgname $luksroot || return
  if [[ $label_opt ]]; then
    (( optsize = 32768 ))
  else
    (( optsize = 0 ))
  fi
  (( rootsize = pvrootsize / 2 ))
  (( rootsize > 65536 && ( rootsize = 65536 ) ))
  (( rootsize < 8192 && ( rootsize = 8192 ) ))
  (( homesize = pvrootsize / 2 ))
  while (( homesize + optsize + rootsize + 64 > pvrootsize )); do
    (( homesize -= 16 ))
    (( rootsize > 9216 && ( rootsize -= 16 ) ))
  done
  (( homesize > 262144 && ( homesize = 262144 ) ))
  (( homesize >= 1024 )) || return
  lvcreate --size ${rootsize}M --name $label_root $vgname || return
  lvcreate --size ${homesize}M --name $label_home $vgname || return
  if [[ $label_opt ]]; then
    lvcreate --size ${optsize}M --name $label_opt $vgname || return
    mkfs.ext4 -q -L $vgname-$label_opt /dev/mapper/$vgname-$label_opt <<< y || return
  fi
  mkfs.ext4 -q -L $vgname-$label_root /dev/mapper/$vgname-$label_root <<< y || return
  mkfs.ext4 -q -L $vgname-$label_home /dev/mapper/$vgname-$label_home <<< y || return
}

ask_existing_lukskey() {
  local REPLY pvroot pvname
  pvname=$(get_config .storage.luks_lvm.pvname) || return
  pvroot=$(blkid --label $pvname) || return
  echo "Found $pvname: $pvroot"
  read -rsp "Enter lukskey, or leave empty to wipe: "
  echo
  if [[ -z $REPLY ]]; then
    echo -n "" > $installbase/lukskey
    return 1
  fi
  echo -n "$REPLY" > $installbase/lukskey
  chmod 600 $installbase/lukskey
  cryptsetup luksOpen -q --disable-external-tokens --key-file $installbase/lukskey --test-passphrase $pvroot
}

sensible_rootsize() {
  local pvrootsize homesize optsize vgname label_home label_opt
  vgname=$(get_config .storage.luks_lvm.vgname) || return
  label_home=$(get_config .storage.luks_lvm.partition.home) || return
  label_opt=$(get_config .storage.luks_lvm.partition.opt) || return
  [[ -e /dev/mapper/$vgname-$label_home ]] || return
  pvrootsize=$(get_pvrootsize)
  homesize=$(lvs --units b --reportformat json_std | jq -r ".report[0].lv[]|select(.lv_name==\"$label_home\").lv_size" | sed -E 's/^(.*)B$/\1/')
  if [[ -e /dev/mapper/$vgname-$label_opt ]]; then
    optsize=$(lvs --units b --reportformat json_std | jq -r ".report[0].lv[]|select(.lv_name==\"$label_opt\").lv_size" | sed -E 's/^(.*)B$/\1/')
    (( optsize /= ( 1024 * 1024 ) ))
  elif [[ $label_opt ]]; then
    (( optsize = 32768 ))
  else
    (( optsize = 0 ))
  fi
  (( homesize /= ( 1024 * 1024 ) ))
  (( rootsize = 65536 ))
  while (( homesize + rootsize + optsize + 64 > pvrootsize )); do
    (( rootsize -= 1024 ))
  done
  (( rootsize >= 8192 )) || return
  echo $rootsize
}

preserve_home() {
  [[ -f $installbase/lukskey ]] || return 1
  local pvroot luks_root efisys label_home label_opt label_root label_efi pvname vgname rootsize optsize
  pvname=$(get_config .storage.luks_lvm.pvname) || return
  vgname=$(get_config .storage.luks_lvm.vgname) || return
  label_home=$(get_config .storage.luks_lvm.partition.home) || return
  label_opt=$(get_config .storage.luks_lvm.partition.opt)
  label_root=$(get_config .storage.luks_lvm.partition.root) || return
  label_efi=$(get_config .storage.luks_lvm.partition.efi) || return
  efisys=$(blkid --label $label_efi) || return
  pvroot=$(blkid --label $pvname) || return
  cryptsetup luksOpen -q --disable-external-tokens --key-file $installbase/lukskey $pvroot $vgname || return
  vgchange -ay $vgname
  [[ -e /dev/mapper/$vgname-$label_home ]] || return
  if [[ ! -e /dev/mapper/$vgname-$label_root ]]; then
    rootsize=$(sensible_rootsize) || return
    lvcreate --size ${rootsize}M --name $label_root $vgname || return
  fi
  mkfs.ext4 -q -L $vgname-$label_root /dev/mapper/$vgname-$label_root <<< y || return
  if [[ -n $label_opt && ! -e /dev/mapper/$vgname-$label_opt ]]; then
    (( optsize = 32768 ))
    lvcreate --size ${optsize}M --name $label_opt $vgname || return
    mkfs.ext4 -q -L $vgname-$label_opt /dev/mapper/$vgname-$label_opt <<< y || return
  fi
  e2label /dev/mapper/$vgname-$label_home $vgname-$label_home || return
  if [[ -e /dev/mapper/$vgname-$label_opt ]]; then
    e2label /dev/mapper/$vgname-$label_opt $vgname-$label_opt || return
  fi
  mkfs.vfat -n $label_efi -F 32 $efisys || return
}

wipe() {
  local REPLY
  while :; do
    read -rp "Erase all data on $(get_disk)? [y/N] "
    if [[ $REPLY =~ [yY] ]]; then
      break
    elif [[ $REPLY =~ [nN] ]]; then
      echo "Installation halted."
      sleep inf
    fi
  done
  create_partitions
}

prepare_partitions() {
  local pvname
  pvname=$(get_config .storage.luks_lvm.pvname) || return
  if ! blkid --label $pvname &> /dev/null; then
    echo "No such partition: $pvname"
    wipe
    return
  fi
  while :; do
    if ask_existing_lukskey; then
      preserve_home
      return
    elif is_empty_file $installbase/lukskey; then
      wipe
      return
    fi
  done
}

return 2> /dev/null || {
  prepare_partitions
}
