#!/bin/bash
#
# This runs very early.
# Its job is to make sure that the partitions named in the profile config exist,
# are formatted and labeled, but not mounted yet.

[[ -v installbase ]] || source /var/tmp/install/common.sh

get_pvrootsize() {
  local efisize=2044 disksize
  disksize=$(get_disksize)
  echo $(( disksize - efisize - 32 ))
}

print_parted_commands() {
  local efisize=2044 pos=4 pvrootsize pvname
  pvrootsize=$(get_pvrootsize)
  pvname=$(get_config .storage.luks_lvm.pvname)
  echo "mklabel gpt"
  echo "mkpart EFISYS fat32 ${pos}MiB $(( pos + efisize ))MiB"
  (( pos += efisize ))
  echo "set 1 esp on"
  echo "mkpart $pvname ext4 ${pos}MiB $(( pos + pvrootsize ))MiB"
  (( pos += pvrootsize ))
}

ask_new_lukskey() {
  local lukskey
  ask_new_key "lukskey" lukskey || return
  echo -n "$lukskey" > $installbase/lukskey
  chmod 600 $installbase/lukskey
}

create_basic_partitions() {
  local disk pvroot luksroot pvname vgname
  pvname=$(get_config .storage.luks_lvm.pvname) || return
  vgname=$(get_config .storage.luks_lvm.vgname) || return
  while :; do
    ask_new_lukskey && break
  done
  disk=$(get_disk) || return
  parted --script --align optimal $disk -- $(print_parted_commands) || return 
  sleep 5
  pvroot=$(by_partlabel $pvname)
  cryptsetup luksFormat --force-password --batch-mode $pvroot $installbase/lukskey || return
  cryptsetup luksOpen --batch-mode --key-file=$installbase/lukskey $pvroot $vgname || return
  cryptsetup config $pvroot --label $pvname || return
  luksroot=$(get_only_child $pvroot) || return
  pvcreate $luksroot || return
  vgcreate $vgname $luksroot || return
}

create_partitions_tasks() {
  local pvrootsize rootsize homesize optsize swapsize label_home label_opt label_root label_efi label_swap pvname vgname acc="[]"
  swapsize=$(get_ram_mb) || return
  (( swapsize += 2048 ))
  pvrootsize=$(get_pvrootsize)
  pvname=$(get_config .storage.luks_lvm.pvname) || return
  vgname=$(get_config .storage.luks_lvm.vgname) || return
  label_home=$(get_config .storage.luks_lvm.partition.home) || return
  label_opt=$(get_config .storage.luks_lvm.partition.opt) || return
  label_root=$(get_config .storage.luks_lvm.partition.root) || return
  label_swap=$(get_config .storage.luks_lvm.partition.swap) || return
  label_efi=$(get_config .storage.luks_lvm.partition.efi) || return
  if [[ $label_opt ]] && (( pvrootsize > 131072 )); then
    (( optsize = 8192 ))
  else
    (( optsize = 0 ))
  fi
  (( rootsize = pvrootsize / 2 ))
  (( rootsize > 32768 && ( rootsize = 32768 ) ))
  (( rootsize < 8192 && ( rootsize = 8192 ) ))
  (( homesize = pvrootsize / 2 ))
  while (( homesize + optsize + swapsize + rootsize + 512 > pvrootsize )); do
    (( homesize -= 64 ))
    (( rootsize > 9216 && ( rootsize -= 64 ) ))
  done
  while (( homesize < 8192 )); do
    (( homesize += 64 ))
    (( swapsize -= 64 ))
  done
  (( homesize > 262144 && ( homesize = 262144 ) ))
  (( rootsize >= 8192 )) || return
  (( homesize >= 1024 )) || return
  (( swapsize >= 1024 )) || return
  (( homesize + rootsize + optsize + swapsize + 512 <= pvrootsize )) || return
  acc=$(jm "$acc" task=wipe dev=$(by_partlabel EFISYS) t=efi label=$label_efi)
  acc=$(jm "$acc" task=create size=$rootsize t=ext4 vgname=$vgname name=$label_root)
  acc=$(jm "$acc" task=create size=$homesize t=ext4 vgname=$vgname name=$label_home)
  acc=$(jm "$acc" task=create size=$swapsize t=swap vgname=$vgname name=$label_swap)
  if [[ $label_opt ]]; then
    acc=$(jm "$acc" task=create size=$optsize t=ext4 vgname=$vgname name=$label_opt)
  fi
  jq -cM ".[]" <<< "$acc"
}

ask_existing_lukskey() {
  local REPLY pvroot pvname
  pvname=$(get_config .storage.luks_lvm.pvname) || return
  pvroot=$(blkid --label $pvname) || return
  echo "Found $pvname: $pvroot"
  read -rsp "Enter lukskey, or leave empty to wipe: "
  echo
  if [[ -z $REPLY ]]; then
    echo -n "" > $installbase/lukskey
    return 1
  fi
  echo -n "$REPLY" > $installbase/lukskey
  chmod 600 $installbase/lukskey
  cryptsetup luksOpen -q --disable-external-tokens --key-file $installbase/lukskey --test-passphrase $pvroot
}

sensible_sizes() {
  local pvrootsize homesize swapsize optsize vgname label_home label_opt
  swapsize=$(get_ram_mb) || return
  (( swapsize += 2048 ))
  vgname=$(get_config .storage.luks_lvm.vgname) || return
  label_home=$(get_config .storage.luks_lvm.partition.home) || return
  label_opt=$(get_config .storage.luks_lvm.partition.opt) || return
  [[ -e /dev/mapper/$vgname-$label_home ]] || return
  pvrootsize=$(get_pvrootsize)
  homesize=$(lvs $vgname --units b --reportformat json_std | jq -r ".report[0].lv[]|select(.lv_name==\"$label_home\").lv_size" | sed -E 's/^(.*)B$/\1/')
  if [[ -e /dev/mapper/$vgname-$label_opt ]]; then
    optsize=$(lvs $vgname --units b --reportformat json_std | jq -r ".report[0].lv[]|select(.lv_name==\"$label_opt\").lv_size" | sed -E 's/^(.*)B$/\1/')
    (( optsize /= ( 1024 * 1024 ) ))
  elif [[ $label_opt ]]; then
    (( optsize = 8192 ))
  else
    (( optsize = 0 ))
  fi
  (( homesize /= ( 1024 * 1024 ) ))
  (( rootsize = 32768 ))
  while (( homesize + rootsize + optsize + swapsize + 512 > pvrootsize )); do
    (( rootsize -= 1024 ))
  done
  if (( rootsize < 16384 )) && [[ ! -e /dev/mapper/$vgname-$label_opt ]]; then
    (( rootsize += optsize ))
    (( optsize = 0 ))
  fi
  while (( rootsize < 8192 )); do
    (( rootsize += 64 ))
    (( swapsize -= 64 ))
  done
  (( rootsize >= 8192 )) || return
  (( swapsize >= 1024 )) || return
  (( homesize + rootsize + optsize + swapsize + 512 <= pvrootsize )) || return
  jq -cM -n "{root:$rootsize,swap:$swapsize,opt:$optsize,home:$homesize}"
}

preserve_home_tasks() {
  local pvroot luks_root efisys label_home label_swap label_opt label_root label_efi pvname vgname rootsize swapsize optsize sizes acc="[]"
  pvname=$(get_config .storage.luks_lvm.pvname) || return
  vgname=$(get_config .storage.luks_lvm.vgname) || return
  label_home=$(get_config .storage.luks_lvm.partition.home) || return
  label_opt=$(get_config .storage.luks_lvm.partition.opt)
  label_root=$(get_config .storage.luks_lvm.partition.root) || return
  label_efi=$(get_config .storage.luks_lvm.partition.efi) || return
  label_swap=$(get_config .storage.luks_lvm.partition.swap) || return
  efisys=$(blkid --label $label_efi) || return
  pvroot=$(blkid --label $pvname) || return
  [[ -e /dev/mapper/$vgname-$label_home ]] || return
  sizes=$(sensible_sizes) || return
  rootsize=$(jq -r ".root | select(. != null)" <<< "$sizes")
  swapsize=$(jq -r ".swap | select(. != null)" <<< "$sizes")
  optsize=$(jq -r ".opt | select(. != null)" <<< "$sizes")
  acc=$(jm "$acc" task=wipe dev=$efisys t=efi label=$label_efi)
  if [[ -e /dev/mapper/$vgname-$label_root ]]; then
    acc=$(jm "$acc" task=wipe dev=/dev/mapper/$vgname-$label_root t=ext4 label=$vgname-$label_root)
  else
    acc=$(jm "$acc" task=create size=$rootsize t=ext4 vgname=$vgname name=$label_root)
  fi
  if (( optsize > 0 )); then
    if [[ -e /dev/mapper/$vgname-$label_opt ]]; then
      acc=$(jm "$acc" task=preserve dev=/dev/mapper/$vgname-$label_opt t=ext4 label=$vgname-$label_opt)
    else
      acc=$(jm "$acc" task=create size=$optsize t=ext4 vgname=$vgname name=$label_opt)
    fi
  elif [[ -n $label_opt && -e /dev/mapper/$vgname-$label_opt ]]; then
    acc=$(jm "$acc" task=drop vgname=$vgname name=$label_opt)
  fi
  acc=$(jm "$acc" task=drop vgname=$vgname name=$label_swap)
  acc=$(jm "$acc" task=create size=$swapsize t=swap vgname=$vgname name=$label_swap)
  acc=$(jm "$acc" task=preserve dev=/dev/mapper/$vgname-$label_home t=ext4 label=$vgname-$label_home)
  jq -cM ".[]" <<< "$acc"
}

wipe() {
  local REPLY
  while :; do
    echo "THE INSTALLER WILL NOW ERASE ALL DATA ON $(get_disk)."
    read -rp "IS THIS OK? [y/N] "
    if [[ $REPLY =~ [yY] ]]; then
      break
    elif [[ $REPLY =~ [nN] ]]; then
      return 1
    fi
  done
  run create_basic_partitions || return
  run_storage_tasks "$(create_partitions_tasks)"
}

open_luks() {
  local pvroot pvname vgname
  pvname=$(get_config .storage.luks_lvm.pvname) || return
  pvroot=$(blkid --label $pvname) || return
  vgname=$(get_config .storage.luks_lvm.vgname) || return
  [[ $pvroot ]] || return
  cryptsetup luksOpen -q --disable-external-tokens --key-file $installbase/lukskey $pvroot $vgname || return
  vgchange -ay $vgname
}

prepare_partitions() {
  local pvname
  pvname=$(get_config .storage.luks_lvm.pvname) || return
  if ! blkid --label $pvname &> /dev/null; then
    echo "No such partition: $pvname"
    wipe
    return
  fi
  while :; do
    if ask_existing_lukskey; then
      run open_luks || return
      run_storage_tasks "$(preserve_home_tasks)"
      return
    elif is_empty_file $installbase/lukskey; then
      wipe
      return
    fi
  done
}

return 2> /dev/null || {
  prepare_partitions
}
