#!/bin/bash

[[ -v installbase ]] || source /var/tmp/install/common.sh

enable_updates() {
  enable_repo fedora-updates.repo
  enable_repo fedora-updates-testing.repo
  enable_repo rpmfusion-free-updates.repo
  enable_repo rpmfusion-free-updates-testing.repo
}

firstboot_script() {
  run set_timezone || return
  run set_rtc_utc || return
  run enable_updates || return
}

return 2> /dev/null || {
  firstboot_script
}

:
