#!/bin/bash

[[ -v installbase ]] || source /var/tmp/install/common.sh

enable_updates() {
  enable_repo fedora-updates.repo
  enable_repo fedora-updates-testing.repo
  enable_repo rpmfusion-free-updates.repo
  enable_repo rpmfusion-free-updates-testing.repo
}

firstboot_script() {
  run set_timezone || return
  run set_rtc_utc || return
  run enable_updates || return
}

return 2> /dev/null || {
  echo Running: $0
  set -o pipefail
  mkdir -p /var/log/pflaster
  firstboot_script 2>&1 | tee /var/log/pflaster/firstboot.txt
}

:
