#!/bin/bash
#
# This runs chrooted, after kernel install.

[[ -v installbase ]] || source /var/tmp/install/common.sh

configure_sudoers() {
  chmod 640 /etc/sudoers
  sed -i -E 's/^%wheel\b.*/%wheel ALL=(ALL) NOPASSWD: ALL/' /etc/sudoers
  chmod 440 /etc/sudoers
}

configure_sdboot() {
  echo "timeout 30" >> /boot/efi/loader/loader.conf
}

configure_tpm_unlocking() {
  has_tpm || return 0
  [[ -f $installbase/lukskey ]] || return
  local device=$(blkid --label pvroot)
  systemd-cryptenroll --wipe-slot tpm2 --tpm2-device auto --tpm2-pcrs "" --unlock-key-file $installbase/lukskey $device || return
  dracut --quiet -f --kver $(uname -r)
}

do_postinstall() {
  run create_users || return
  run set_root_pw || return
  run enable_firstboot || return
  run configure_sudoers || return
  run configure_sdboot || return
  run configure_tpm_unlocking || return
}

return 2> /dev/null || {
  do_postinstall
}
