#!/bin/bash
#
# chrooted

[[ -v installbase ]] || source /var/tmp/install/common.sh

do_postinstall() {
  run loadkeys_config || return
  run set_nopasswd || return
}

return 2> /dev/null || {
  do_postinstall
}
