#!/bin/bash
#
# chrooted

[[ -v installbase ]] || source /var/tmp/install/common.sh

configure_crypttab() {
  mkdir -p /etc
  local pvname uuid_pvroot
  pvname=$(get_config .storage.luks_lvm.pvname) || return
  uuid_pvroot=$(get_uuid $pvname)
  echo "luks UUID=$uuid_pvroot none discard,tpm2-device=auto" > /etc/crypttab
}

print_fstab() {
  local label_home label_opt label_root label_efi uuid_home uuid_root uuid_opt uuid_efi vgname
  label_home=$(get_config .storage.luks_lvm.partition.home)
  label_opt=$(get_config .storage.luks_lvm.partition.opt)
  label_root=$(get_config .storage.luks_lvm.partition.root)
  label_efi=$(get_config .storage.luks_lvm.partition.efi)
  vgname=$(get_config .storage.luks_lvm.vgname)
  uuid_efi=$(get_uuid $label_efi)
  uuid_root=$(get_uuid $vgname-$label_root)
  uuid_opt=$(get_uuid $vgname-$label_opt)
  uuid_home=$(get_uuid $vgname-$label_home)
  [[ $uuid_efi ]] || return
  [[ $uuid_root ]] || return
  [[ $uuid_home ]] || return
  [[ $uuid_opt ]] || return
  echo "UUID=$uuid_efi  /boot/efi vfat umask=0077,shortname=winnt 0 2"
  echo "UUID=$uuid_root /         ext4 defaults 1 2"
  echo "UUID=$uuid_home /home     ext4 defaults 1 2"
  echo "UUID=$uuid_opt  /opt      ext4 defaults 1 2"
}

configure_fstab() {
  mkdir -p /etc
  print_fstab >> /etc/fstab
}

print_cmdline_options() {
  local uuid_root uuid_pvroot label_root pvname vgname
  label_root=$(get_config .storage.luks_lvm.partition.root)
  pvname=$(get_config .storage.luks_lvm.pvname) || return
  vgname=$(get_config .storage.luks_lvm.vgname)
  [[ $vgname ]] || return
  uuid_root=$(get_uuid $vgname-$label_root)
  uuid_pvroot=$(get_uuid $pvname)
  [[ $uuid_root ]] || return
  [[ $uuid_pvroot ]] || return
  echo "root=UUID=$uuid_root"
  echo "rd.luks.uuid=$uuid_pvroot"
  echo "rd.lvm.vg=$vgname"
  echo "rd.shell"
}

configure_cmdline() {
  local options
  mkdir -p /etc/kernel
  options=$(print_cmdline_options | tr '\n' ' ')
  echo ${options% } > /etc/kernel/cmdline
}

preinstall() {
  run configure_crypttab || return
  run configure_fstab || return
  run configure_cmdline || return
}

return 2> /dev/null || {
  preinstall
}
