#!/bin/bash
#
# This script is used for testing purposes.

(( $EUID == 0 )) || { echo "needs root" ; exit 1 ; }

install -d $(dirname $0)/var/tmp/install /var/tmp/install
cp -r $(dirname $0)/var/tmp/install /var/tmp
