#!/bin/bash
#
# This script is used for testing purposes.

my_ip=$(hostname -I | sed -n -E 's/.*\b([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\b.*/\1/p')
[[ $my_ip ]] || { echo "something wrong" ; exit 1 ; }
python3 -m http.server --bind $my_ip 3001
