#!/bin/bash
#
# Some things don't work in a chroot, so do them here.

[[ -v installbase ]] || source /var/tmp/install/common.sh

install_kde() {
  local groups=(
    kde-desktop
    fonts
    base-graphical
  )
  echo "dnf install group ${groups[@]}"
  dnf -qy --color=never \
      -x grub2-common \
      -x grub2-pc \
      -x grub2-pc-modules \
      -x grub2-efi-x64 \
      -x grub2-tools \
      -x grub2-tools-minimal \
      -x grub2-tools-extra \
      -x grub2-tools-efi \
      group install "${groups[@]}"
}

firstboot_script() {
  run install_kde || return
  run set_enforcing || return
  run trigger_autorelabel || return
  run set_target_graphical || return
  [[ -f /tmp/stop ]] && { echo "Halted. 'stop -c' to continue" ; sleep inf ; }
  systemctl reboot
}

return 2> /dev/null || {
  echo Running: $0
  set -o pipefail
  mkdir -p /var/log/pflaster
  firstboot_script 2>&1 | tee /var/log/pflaster/firstboot.txt
}

:
