#!/bin/bash

[[ -v installbase ]] || source /var/tmp/install/common.sh

install_more_groups() {
  local groups=(
    kde-desktop
    fonts
    base-graphical
    hardware-support
    standard
  )
  echo "dnf install group ${groups[@]}"
  dnf -qy --color=never \
      -x PackageKit-command-not-found \
      -x ksshaskpass \
      -x plasma-welcome \
      -x fedora-workstation-repositories \
      -x grub2-common \
      -x grub2-pc \
      -x grub2-pc-modules \
      -x grub2-efi-x64 \
      -x grub2-tools \
      -x grub2-tools-minimal \
      -x grub2-tools-extra \
      -x grub2-tools-efi \
      group install "${groups[@]}"
}

install_more_software() {
  local packs=(
    git
    mousepad
    ugrep
    ffmpeg
    x264-libs
    x265-libs
    gutenprint
    portaudio
    NetworkManager-wifi
    liberation-sans-fonts
    liberation-serif-fonts
    gdouros-symbola-fonts
    google-noto-emoji-fonts
    mokutil
    highcontrast-icon-theme
    im-chooser
    libadwaita
    libva-intel-media-driver
    qt6-qtwayland-adwaita-decoration
    mozjs128
    mozjs140
    kwebkitpart
    SDL2_ttf
    breeze-icon-theme-fedora
    gstreamer1-plugin-dav1d
    gstreamer1-plugins-bad-freeworld
    gstreamer1-plugins-ugly
    gstreamer1-plugins-ugly-free
    cpuinfo
    pipewire-utils
    pipewire-gstreamer
    pipewire-config-raop
    pipewire-codec-aptx
  )
  echo "dnf install ${packs[@]}"
  dnf -qy --color=never install "${packs[@]}"
}

disable_updates() {
  disable_repo fedora-updates.repo
  disable_repo fedora-updates-testing.repo
  disable_repo rpmfusion-free-updates-testing.repo
  disable_repo rpmfusion-free-updates.repo
  disable_repo google-chrome.repo
}

enable_updates() {
  enable_repo fedora-updates.repo
  enable_repo fedora-updates-testing.repo
  enable_repo rpmfusion-free-updates.repo
  enable_repo rpmfusion-free-updates-testing.repo
}

firstboot_script() {
  run set_timezone || return
  run set_rtc_utc || return
  run disable_updates || return
  run install_more_groups || return
  run disable_updates || return
  run install_more_software || return
  run enable_updates || return
  run set_enforcing || return
  run trigger_autorelabel || return
  reboot
}

return 2> /dev/null || {
  echo Running: $0
  set -o pipefail
  mkdir -p /var/log/pflaster
  firstboot_script 2>&1 | tee /var/log/pflaster/firstboot.txt
}

:
