#!/bin/bash
#
# chrooted

[[ -v installbase ]] || source /var/tmp/install/common.sh

postgroups() {
  disable_repo fedora-updates.repo
  disable_repo fedora-updates-testing.repo
  disable_repo rpmfusion-free-updates.repo
  disable_repo rpmfusion-nonfree-nvidia-driver.repo
  disable_repo rpmfusion-nonfree-steam.repo
  disable_repo rpmfusion-free.repo
  disable_repo rpmfusion-free-updates-testing.repo
  disable_repo fedora-cisco-openh264.repo
  disable_repo google-chrome.repo
}

return 2> /dev/null || {
  postgroups
}
