#!/bin/bash

do_postinstall() {
  kernel-install add -v || return 1
  useradd -m -g wheel -p '$y$j9T$el9zAYHYnL4Oq7jQ9eeYx/$wK0wzF89ZEiy5/WBN1LEnEdeDExDlHofqT/BUzjriS2' core
}

return || {
  do_postinstall
}
