#!/bin/bash

[[ -v installbase ]] || source /tmp/install/common.sh

get_config() {
  jq -r "$1" "$installbase/config.json"
}

get_users() {
  jq -r '.users | keys[]' "$installbase/config.json"
}

create_user() {
  local sshkey user=$1
  useradd -m -U -p "$(get_config .users.$user.password)" "$user"
  if [[ $(get_config .users.$user.admin) = "true" ]]; then
    usermod -a -G wheel "$user"
  fi
  sshkey="$(get_config .users.$user.sshkey)"
  if [[ ${sshkey:-null} != "null" ]]; then
    mkdir -p /home/$user/.ssh
    chmod 700 /home/$user/.ssh
    echo "$sshkey" > /home/$user/.ssh/authorized_keys
    chmod 600 /home/$user/.ssh/authorized_keys
  fi
  mkdir -p /home/$user/.bashrc.d
  echo "alias ll='ls -lAZ --color=auto'" > /home/$user/.bashrc.d/aliases.sh
  chown -R $user: /home/$user
}

create_users() {
  local user users=$(get_users)
  for user in "$users"; do
    create_user $user
  done
}

set_root_pw() {
  local rootpw
  rootpw=$(get_config .rootpw)
  if [[ ${rootpw:-null} = "null" ]]; then
    return 0
  fi
  chmod 600 /etc/shadow
  sed -i -E "s@^root:\!unprovisioned:(.*)@root:$rootpw:\1@" /etc/shadow
  chmod 000 /etc/shadow
}

configure_sudoers() {
  chmod 640 /etc/sudoers
  sed -i -E 's/^%wheel\b.*/%wheel ALL=(ALL) NOPASSWD: ALL/' /etc/sudoers
  chmod 440 /etc/sudoers
}

configure_sdboot() {
  echo "timeout 30" >> /boot/efi/loader/loader.conf
}

configure_tpm_unlocking() {
  has_tpm || return 0
  local device=$(blkid --label pvroot)
  echo -n temppass > /tmp/temppass
  chmod 600 /tmp/temppass
  systemd-cryptenroll --wipe-slot tpm2 --tpm2-device auto --tpm2-pcrs "" --unlock-key-file /tmp/temppass $device || return 1
  dracut --quiet -f --kver $(uname -r)
}

do_postinstall() {
  create_users || return $(error "create users")
  set_root_pw || return $(error "set root pw")
  configure_sudoers || return $(error "configure sudoers")
  configure_sdboot || return $(error "configure sudoers")
  configure_tpm_unlocking
}

return 2> /dev/null || {
  do_postinstall
}
