#!/bin/bash
#
# A profile may or may not have this file.
# If it exists, it runs unchrooted,
# between "sysroot" mount and "postmount" script.

dnf_config() {
  for repo in /etc/yum.repos.d/*.repo; do
    sed -i -E \
      -e "s|^countme=.*|countme=0|" \
      $repo
  done
}

return 2> /dev/null || {
  dnf_config
}
