#!/bin/bash
#
# A profile may or may not have this file.
# If it exists, it runs unchrooted,
# between "sysroot" mount and kernel install.
# dnf is already configured at this point.

[[ -v installbase ]] || source /tmp/install/common.sh

copy_lukskey() {
  [[ -f $installbase/lukskey ]] || return 1
  mkdir -p $sysroot$installbase
  cp $installbase/lukskey $sysroot$installbase
}

configure_hostname() {
  mkdir -p $sysroot/etc
  local hostname="$(get_config .hostname)"
  hostname="${hostname:-box}"
  hostnamectl hostname $hostname || return
  echo $hostname > $sysroot/etc/hostname
}

postmount() {
  run copy_lukskey || return
  run configure_hostname || return
}

return 2> /dev/null || {
  postmount
}
