#!/bin/bash
#
# This runs chrooted.
# Preinstall means right before ""kernel"" install.

[[ -v installbase ]] || source /tmp/install/common.sh

configure_crypttab() {
  mkdir -p /etc
  echo "luks UUID=$(get_uuid pvroot) none discard,tpm2-device=auto" > /etc/crypttab
}

print_fstab() {
  echo "UUID=$(get_uuid $(get_label efi))  /boot/efi vfat umask=0077,shortname=winnt 0 2"
  echo "UUID=$(get_uuid $(get_label root)) /         ext4 defaults 1 2"
  echo "UUID=$(get_uuid $(get_label home)) /home     ext4 defaults 1 2"
}

configure_fstab() {
  mkdir -p /etc
  print_fstab >> /etc/fstab
}

print_cmdline_options() {
  echo "root=UUID=$(get_uuid $(get_label root))"
  echo "rd.luks.uuid=$(get_uuid pvroot)"
  echo "rd.lvm.vg=luks"
  echo "rd.shell"
}

configure_cmdline() {
  mkdir -p /etc/kernel
  local options=$(print_cmdline_options | tr '\n' ' ')
  echo ${options% } > /etc/kernel/cmdline
}

do_prepare() {
  run configure_crypttab || return
  run configure_fstab || return
  run configure_cmdline || return
}

return 2> /dev/null || {
  do_prepare
}
