#!/bin/bash
#
# This runs very early. Before preinstall.
# Its job is to make sure that the partitions named in the profile config exist,
# are formatted and labeled, but not mounted yet.

[[ -v installbase ]] || source /tmp/install/common.sh

get_disksize() {
  local disk bytes
  disk=$(get_disk) || return $(error "get_disk")
  bytes=$(lsblk -b -n --filter "PATH == '$disk'" -o SIZE)
  echo $(( bytes / ( 1024 * 1024 ) ))
}

get_only_child() {
  [[ $1 ]] || return $(error "param: PATH")
  local kname children
  kname=$(lsblk -n --filter "PATH == '$1'" -o KNAME)
  children=$(lsblk -n --filter "PKNAME == '$kname'" -o PATH | tr '\n' ' ')
  children=${children% }
  [[ $children = "${children// /}" ]] || return $(error "more than one child")
  echo $children
}

print_parted_commands() {
  local disksize efizsize
  disksize=$(get_disksize)
  efisize=$(get_config .profile.lvm_luks.partition.efi.defaultsize)
  efisize=${efisize:-2044}
  local pvrootsize=$(( disksize - efisize - 32 ))
  local pos=4
  echo "mklabel gpt"
  echo "mkpart EFISYS fat32 ${pos}MiB $(( pos + efisize ))MiB"
  (( pos += efisize ))
  echo "set 1 esp on"
  echo "mkpart pvroot ext4 ${pos}MiB $(( pos + pvrootsize ))MiB"
  (( pos += pvrootsize ))
}

ask_new_lukskey() {
  local reply0 reply1
  read -rsp "Choose lukskey: " reply0
  echo
  (( ${#reply0} >= 8 )) || return $(error "minimum 8 characters")
  [[ $reply0 = "${reply0// /}" ]] || return $(error "spaces not allowed")
  read -rsp "Confirm lukskey: " reply1
  echo
  [[ $reply0 = "$reply1" ]] || return $(error "confirmation failed")
  echo -n "$reply0" > $installbase/lukskey
  chmod 600 $installbase/lukskey
}

create_partitions() {
  local disk part pvroot luksroot rootsize homesize label_home label_root label_efi
  label_home=$(get_config .profile.lvm_luks.partition.home.label) || return
  label_root=$(get_config .profile.lvm_luks.partition.root.label) || return
  label_efi=$(get_config .profile.lvm_luks.partition.efi.label) || return
  [[ $label_home = luks-* ]] || return $(error "invalid label: $label_home")
  [[ $label_root = luks-* ]] || return $(error "invalid label: $label_root")
  while true; do
    ask_new_lukskey && break
  done
  disk=$(get_disk) || return $(error "get_disk")
  parted --script --align optimal $disk -- $(print_parted_commands) || return 
  mkfs.vfat -n $label_efi -F 32 $(by_partlabel EFISYS) || return
  pvroot=$(by_partlabel pvroot)
  cryptsetup luksFormat --force-password --batch-mode $pvroot $installbase/lukskey || return
  cryptsetup luksOpen --batch-mode --key-file=$installbase/lukskey $pvroot luks || return
  cryptsetup config $pvroot --label pvroot || return
  luksroot=$(get_only_child $pvroot) || return
  pvcreate $luksroot || return
  vgcreate luks $luksroot || return
  rootsize=$(get_config .profile.lvm_luks.partition.root.defaultsize)
  homesize=$(get_config .profile.lvm_luks.partition.home.defaultsize)
  lvcreate -L ${rootsize:-8192}M -n ${label_root#luks-} luks || return
  lvcreate -L ${homesize:-2048}M -n ${label_home#luks-} luks || return
  mkfs.ext4 -q -L $label_root /dev/mapper/$label_root <<< y || return
  mkfs.ext4 -q -L $label_home /dev/mapper/$label_home <<< y || return
}

ask_existing_lukskey() {
  local REPLY pvroot
  pvroot=$(blkid --label pvroot 2> /dev/null) || return 1
  echo "Found pvroot: $pvroot"
  read -rsp "Enter lukskey, or leave empty to wipe: "
  echo
  [[ -z $REPLY ]] && return 125
  echo -n "$REPLY" > $installbase/lukskey
  chmod 600 $installbase/lukskey
  cryptsetup luksOpen -q --disable-external-tokens --key-file $installbase/lukskey --test-passphrase $pvroot
}

unlock_pvroot() {
  [[ -f $installbase/lukskey ]] || return 1
  local pvroot luks_root efisys label_home label_root label_efi
  label_home=$(get_config .profile.lvm_luks.partition.home.label) || return
  label_root=$(get_config .profile.lvm_luks.partition.root.label) || return
  label_efi=$(get_config .profile.lvm_luks.partition.efi.label) || return
  [[ $label_home = luks-* ]] || return $(error "invalid label: $label_home")
  [[ $label_root = luks-* ]] || return $(error "invalid label: $label_root")
  efisys=$(blkid --label $label_efi) || return
  pvroot=$(blkid --label pvroot 2> /dev/null) || return
  cryptsetup luksOpen -q --disable-external-tokens --key-file $installbase/lukskey $pvroot luks || return
  vgchange -ay
  luksroot=$(blkid --label $label_root) || return
  blkid --label $label_home || return
  mkfs.ext4 -q -L $label_root $luksroot <<< y || return
  mkfs.vfat -n $label_efi -F 32 $efisys || return
}

prepare_partitions() {
  if ! has_modifier "always-wipe" && blkid --label pvroot &> /dev/null; then
    while true; do
      ask_existing_lukskey
      case $? in
        125)
          break
          ;;
        0)
          unlock_pvroot
          return
          ;;
      esac
    done
  fi
  local REPLY
  while true; do
    read -rp "Erase all data on $(get_disk)? [y/N] "
    [[ $REPLY =~ [yY] ]] && break
    [[ $REPLY =~ [nN] ]] && { echo "I sleep." ; sleep inf ; }
  done
  create_partitions
}

return 2> /dev/null || {
  prepare_partitions
}
