#!/bin/bash
#
# This runs very early. Before preinstall.
# Its job is to make sure that the partitions named in the profile config exist,
# are formatted and labeled, but not mounted yet.

[[ -v installbase ]] || source /tmp/install/common.sh

get_disksize() {
  local disk bytes
  disk=$(get_disk) || return $(error "get_disk")
  bytes=$(lsblk -b -n --filter "PATH == '$disk'" -o SIZE)
  echo $(( bytes / ( 1024 * 1024 ) ))
}

get_only_child() {
  [[ $1 ]] || return $(error "param: PATH")
  local kname children
  kname=$(lsblk -n --filter "PATH == '$1'" -o KNAME)
  children=$(lsblk -n --filter "PKNAME == '$kname'" -o PATH | tr '\n' ' ')
  children=${children% }
  [[ $children = "${children// /}" ]] || return $(error "more than one child")
  echo $children
}

print_parted_commands() {
  local disksize efizsize
  disksize=$(get_disksize)
  efisize=$(get_config .profile.lvm_plain.partition.efi.defaultsize)
  efisize=${efisize:-2044}
  local pvrootsize=$(( disksize - efisize - 32 ))
  local pos=4
  echo "mklabel gpt"
  echo "mkpart EFISYS fat32 ${pos}MiB $(( pos + efisize ))MiB"
  (( pos += efisize ))
  echo "set 1 esp on"
  echo "mkpart pvroot ext4 ${pos}MiB $(( pos + pvrootsize ))MiB"
  (( pos += pvrootsize ))
}

create_partitions() {
  local disk part pvroot rootsize homesize label_home label_root label_efi
  label_home=$(get_config .profile.lvm_plain.partition.home.label) || return
  label_root=$(get_config .profile.lvm_plain.partition.root.label) || return
  label_efi=$(get_config .profile.lvm_plain.partition.efi.label) || return
  [[ $label_home = linux-* ]] || return $(error "invalid label: home")
  [[ $label_root = linux-* ]] || return $(error "invalid label: root")
  disk=$(get_disk) || return $(error "get_disk")
  parted --script --align optimal $disk -- $(print_parted_commands) || return 
  mkfs.vfat -n $label_efi -F 32 $(by_partlabel EFISYS) || return
  pvroot=$(by_partlabel pvroot)
  pvcreate $pvroot || return
  vgcreate linux $pvroot || return
  rootsize=$(get_config .profile.lvm_plain.partition.root.defaultsize)
  homesize=$(get_config .profile.lvm_plain.partition.home.defaultsize)
  lvcreate -L ${rootsize:-8192}M -n ${label_root#linux-} linux || return
  lvcreate -L ${homesize:-2048}M -n ${label_home#linux-} linux || return
  mkfs.ext4 -q -L $label_root /dev/mapper/$label_root <<< y || return
  mkfs.ext4 -q -L $label_home /dev/mapper/$label_home <<< y || return
}

format_root() {
  [[ -f $installbase/lukskey ]] || return 1
  local efisys label_home label_root label_efi
  label_home=$(get_config .profile.lvm_plain.partition.home.label) || return
  label_root=$(get_config .profile.lvm_plain.partition.root.label) || return
  label_efi=$(get_config .profile.lvm_plain.partition.efi.label) || return
  [[ $label_home = linux-* ]] || return $(error "invalid label: home")
  [[ $label_root = linux-* ]] || return $(error "invalid label: root")
  efisys=$(blkid --label $label_efi) || return
  linuxroot=$(blkid --label $label_root) || return
  mkfs.ext4 -q -L $label_root $linuxroot <<< y || return
  mkfs.vfat -n $label_efi -F 32 $efisys || return
}

prepare_partitions() {
  local label_home
  vgchange -ay
  label_home=$(get_config .profile.lvm_plain.partition.home.label) || return
  if ! has_modifier "always-wipe" && blkid --label $label_home &> /dev/null; then
    format_root
    return
  fi
  local REPLY
  while true; do
    read -rp "Erase all data on $(get_disk)? [y/N] "
    [[ $REPLY =~ [yY] ]] && break
    [[ $REPLY =~ [nN] ]] && { echo "I sleep." ; sleep inf ; }
  done
  create_partitions
}

return 2> /dev/null || {
  prepare_partitions
}
