#!/bin/bash
#
# This runs chrooted.
# Preinstall means right before ""kernel"" install.

[[ -v installbase ]] || source /tmp/install/common.sh

configure_crypttab() {
  mkdir -p /etc
  echo "luks UUID=$(get_uuid pvroot) none discard,tpm2-device=auto" > /etc/crypttab
}

print_fstab() {
  local label_home label_root label_efi
  label_home=$(get_config .profile.lvm_luks.partition.home.label)
  label_root=$(get_config .profile.lvm_luks.partition.root.label)
  label_efi=$(get_config .profile.lvm_luks.partition.efi.label)
  echo "UUID=$(get_uuid $label_efi)  /boot/efi vfat umask=0077,shortname=winnt 0 2"
  echo "UUID=$(get_uuid $label_root) /         ext4 defaults 1 2"
  echo "UUID=$(get_uuid $label_home) /home     ext4 defaults 1 2"
}

configure_fstab() {
  mkdir -p /etc
  print_fstab >> /etc/fstab
}

print_cmdline_options() {
  local label_root
  label_root=$(get_config .profile.lvm_luks.partition.root.label)
  echo "root=UUID=$(get_uuid $label_root)"
  echo "rd.luks.uuid=$(get_uuid pvroot)"
  echo "rd.lvm.vg=luks"
  echo "rd.shell"
}

configure_cmdline() {
  mkdir -p /etc/kernel
  local options=$(print_cmdline_options | tr '\n' ' ')
  echo ${options% } > /etc/kernel/cmdline
}

do_prepare() {
  run configure_crypttab || return
  run configure_fstab || return
  run configure_cmdline || return
}

return 2> /dev/null || {
  do_prepare
}
