#!/bin/bash

[[ -v installbase ]] || source /var/tmp/install/common.sh

disable_zram() {
  if [[ -e /dev/mapper/$vgname-$label_swap ]]; then
    mkdir -p /etc/systemd
    touch /etc/systemd/zram-generator.conf
  fi
}

do_postinstall() {
  run disable_zram || return
}

return 2> /dev/null || {
  do_postinstall
}
