#!/bin/bash

[[ -v installbase ]] || source /var/tmp/install/common.sh

disable_zram() {
  mkdir -p /etc/systemd
  touch /etc/systemd/zram-generator.conf
}

do_postinstall() {
  run disable_zram || return
}

return 2> /dev/null || {
  do_postinstall
}
