#!/bin/bash

[[ -v installbase ]] || source /var/tmp/install/common.sh

firstboot() {
  local segment file storage software rc=0
  run configure_keyboard || return
  storage=$(get_profile .storage)
  software=$(get_profile .software)
  [[ $storage ]] || return
  [[ $software ]] || return
  for segment in storage/$storage software/$software; do
    file=$installbase/$segment/firstboot
    if [[ -f $file ]]; then
      echo "Running: $file"
      $file || rc=1
    fi
  done
  systemctl enable anyboot.service || return
  if is_swap_on_drive; then
    systemctl disable systemd-oomd || return
  fi
  run set_target_anyboot || return
  rm -f /etc/sysctl.d/10-kernel-quiet.conf
  if [[ -f /tmp/stop ]]; then
    echo "Halted."
    sleep inf
  fi
  return $rc
}

return 2> /dev/null || {
  export NO_COLOR=1
  set -o pipefail
  mkdir -p /var/log/pflaster
  echo Running: $0
  firstboot 2>&1 | tee /var/log/pflaster/firstboot.txt || {
    echo "Halted after error."
    sleep inf
  }
  reboot
}
