#!/bin/bash

[[ -v installbase ]] || source /var/tmp/install/common.sh

firstboot() {
  local segment file storage software rc=0
  storage=$(get_profile .storage)
  software=$(get_profile .software)
  [[ $storage ]] || return
  [[ $software ]] || return
  for segment in storage/$storage software/$software; do
    file=$installbase/$segment/firstboot
    if [[ -f $file ]]; then
      echo "Running: $file"
      $file || rc=1
    fi
  done
  run configure_hostname || return
  systemctl enable anyboot.service || return
  run set_target_anyboot || return
  if [[ -f /tmp/stop ]]; then
    echo "Halted."
    sleep inf
  fi
  return $rc
}

return 2> /dev/null || {
  firstboot || {
    echo "Halted after error."
    sleep inf
  }
  reboot
}
