#!/bin/bash
#
# General postinstall

[[ -v installbase ]] || source /var/tmp/install/common.sh

loadkeys_config() {
  # https://unix.stackexchange.com/questions/85374/loadkeys-gives-permission-denied-for-normal-user
  chmod u+s $(which loadkeys)
}

xdg_user_dirs_config() {
  # use standard names
  if [[ ! -f /etc/locale.conf ]]; then
    return 0
  fi
  if grep -E 'LANG=.*\ben_US\b.*' /etc/locale.conf; then
    return 0
  fi
  if grep -E 'LANG=.*\bC\b.*' /etc/locale.conf; then
    return 0
  fi
  if [[ ! -f /etc/xdg/user-dirs.conf ]]; then
    return 0
  fi
  sed -i 's/^enabled=.*/enabled=False/' /etc/xdg/user-dirs.conf
}

do_postinstall() {
  run loadkeys_config || return
  run set_timezone || return
  run create_users || return
  run set_root_pw || return
  run set_nopasswd || return
  run configure_sdboot || return
  run xdg_user_dirs_config || return
}

return 2> /dev/null || {
  do_postinstall
}
