#!/bin/bash

[[ -v installbase ]] || source /var/tmp/install/common.sh

do_postinstall() {
  run set_root_pw || return
  run create_users || return
  run configure_sdboot || return
  run configure_hostname || return
  run set_target_firstboot || return
}

return 2> /dev/null || {
  do_postinstall
}
