#!/bin/bash

[[ -v installbase ]] || source /var/tmp/install/common.sh

set_root_pw() {
  local rootpw
  rootpw=$(get_profile .rootpw)
  if [[ -z $rootpw ]]; then
    return 0
  fi
  chmod 600 /etc/shadow
  sed -i -E "s@^root:\!unprovisioned:(.*)@root:$rootpw:\1@" /etc/shadow
  chmod 000 /etc/shadow
}

get_users() {
  jq -M -r '.user // {} | keys[]' "$installbase/profile.json"
}

create_user() {
  local user_exists sshkey pw user=$1 useradd_opts=()
  if [[ -e /home/$user ]]; then
    user_exists=1
  fi
  if [[ $user_exists ]]; then
    useradd_opts+=(-m)
  fi
  if [[ $(get_profile .user.$user.system) = "true" ]]; then
    useradd_opts+=(--system)
  fi
  pw=$(get_profile .user.$user.password)
  if [[ $pw ]]; then
    useradd_opts+=(-p "$pw")
  fi
  useradd -U "${useradd_opts[@]}" "$user"
  if [[ $(get_profile .user.$user.admin) = "true" ]]; then
    usermod -a -G wheel "$user"
  fi
  if [[ $user_exists ]]; then
    chown -R $user: /home/$user
    return 0
  fi
  sshkey="$(get_profile .user.$user.sshkey)"
  mkdir -p /home/$user/.ssh
  chmod 700 /home/$user/.ssh
  if [[ $sshkey ]]; then
    echo "$sshkey" > /home/$user/.ssh/authorized_keys
    chmod 600 /home/$user/.ssh/authorized_keys
  fi
  chown -R $user: /home/$user
}

create_users() {
  local user users=$(get_users)
  for user in $users; do
    create_user $user
  done
}

configure_vconsole() {
  local keyboard
  keyboard=$(get_profile .keyboard)
  keyboard=${keyboard:-us}
  if [[ -f /etc/vconsole.conf ]]; then
    if grep -q ^KEYMAP= /etc/vconsole.conf; then
      sed -i -E "s/^KEYMAP=.*/KEYMAP=\"$keyboard\"/" /etc/vconsole.conf
    else
      echo "KEYMAP=\"$keyboard\"" > /etc/vconsole.conf
    fi
  else
    echo "KEYMAP=\"$keyboard\"" > /etc/vconsole.conf
  fi
}

configure_locale() {
  local lang
  lang=$(get_profile .lang)
  lang=${lang:-en_US}
  lang=${lang%.*}.UTF-8
  if [[ -f /etc/locale.conf ]]; then
    if grep -q ^LANG= /etc/locale.conf; then
      sed -i -E "s/^LANG=.*/LANG=\"$lang\"/" /etc/locale.conf
    else
      echo "LANG=\"$lang\"" > /etc/locale.conf
    fi
  else
    echo "LANG=\"$lang\"" > /etc/locale.conf
  fi
}

apply_hostname_config() {
  local hostname
  hostname="$(get_profile .hostname)"
  echo "configuring hostname: $hostname"
  [[ $hostname ]] || return
  echo "$hostname" > /etc/hostname
  hostnamectl hostname $hostname
}

set_permissive() {
  rpm --quiet -q selinux-policy || return 0
  sed -i -E 's/^SELINUX=.*/SELINUX=permissive/' /etc/selinux/config
}

set_target_firstboot() {
  [[ -f /usr/share/systemux/tmux.conf ]] || return
  local software
  software=$(get_profile .software)
  [[ $software ]] || return
  systemctl set-default firstboot.target
  set_permissive
  # sesearch -s init_t -t screen_exec_t -c file -A
  # sesearch -s init_t -t init_t -c file -A
  if [[ -f /usr/bin/tmux ]]; then
    # still needed?
    chcon -t bin_t /usr/bin/tmux
  fi
}

do_postinstall() {
  run set_root_pw || return
  run create_users || return
  run configure_vconsole || return
  run configure_locale || return
  run configure_sdboot || return
  run apply_hostname_config || return
  run set_target_firstboot || return
}

return 2> /dev/null || {
  export NO_COLOR=1
  do_postinstall
}
