#!/bin/bash
#
# This runs very early.
# Its job is to make sure that the partitions named in the profile config exist,
# are formatted and labeled, but not mounted yet.

[[ -v installbase ]] || source /var/tmp/install/common.sh

get_pvrootsize() {
  local disksize efisize=2044
  disksize=$(get_disksize)
  echo $(( disksize - efisize - 32 ))
}

print_parted_commands() {
  local efisize=2044 pos=4 pvrootsize
  pvrootsize=$(get_pvrootsize)
  echo "mklabel gpt"
  echo "mkpart EFISYS fat32 ${pos}MiB $(( pos + efisize ))MiB"
  (( pos += efisize ))
  echo "set 1 esp on"
  echo "mkpart pvroot ext4 ${pos}MiB $(( pos + pvrootsize ))MiB"
  (( pos += pvrootsize ))
}

create_partitions() {
  local disk vgname pvroot pvrootsize rootsize homesize swapsize label_home label_root label_efi label_swap vg max_swapsize
  vgname=$(get_config .storage.plain_lvm.vgname) || return
  vgchange -an $vgname || return
  for vg in $(vgs --noheadings | sed -E 's/^\s*\b(\S+)\b.*/\1/'); do
    if [[ $vg = "$vgname" ]]; then
      vgremove -f $vgname || return
    fi
  done
  max_swapsize=$(get_ram_mb) || return
  (( max_swapsize += 2048 ))
  pvrootsize=$(get_pvrootsize)
  label_home=$(get_config .storage.plain_lvm.partition.home) || return
  label_root=$(get_config .storage.plain_lvm.partition.root) || return
  label_swap=$(get_config .storage.plain_lvm.partition.swap) || return
  label_efi=$(get_config .storage.plain_lvm.partition.efi) || return
  disk=$(get_disk) || return
  parted --script --align optimal $disk -- $(print_parted_commands) || return 
  mkfs.vfat -n $label_efi -F 32 $(by_partlabel EFISYS) || return
  pvroot=$(by_partlabel pvroot) || return
  pvcreate $pvroot || return
  vgcreate $vgname $pvroot || return
  (( swapsize = 1024 ))
  (( rootsize = pvrootsize / 2 ))
  (( rootsize > 65536 && ( rootsize = 65536 ) ))
  (( rootsize < 8192 && ( rootsize = 8192 ) ))
  (( homesize = pvrootsize / 2 ))
  while (( homesize + swapsize + rootsize + 64 > pvrootsize )); do
    (( homesize -= 16 ))
    (( rootsize > 9216 && ( rootsize -= 16 ) ))
  done
  if (( homesize > 262144 )); then
    (( swapsize += ( homesize - 262144 ) ))
    (( homesize = 262144 ))
    (( swapsize > max_swapsize && ( swapsize = max_swapsize ) ))
  fi
  (( homesize >= 1024 )) || return
  lvcreate --size ${rootsize}M --name $label_root $vgname || return
  lvcreate --size ${homesize}M --name $label_home $vgname || return
  lvcreate --size ${swapsize}M --name $label_swap $vgname || return
  mkfs.ext4 -q -L $vgname-$label_root /dev/mapper/$vgname-$label_root <<< y || return
  mkfs.ext4 -q -L $vgname-$label_home /dev/mapper/$vgname-$label_home <<< y || return
  mkswap /dev/mapper/$vgname-$label_swap
}

wipe() {
  local REPLY
  while :; do
    read -rp "Erase all data on $(get_disk)? [y/N] "
    if [[ $REPLY =~ [yY] ]]; then
      break
    elif [[ $REPLY =~ [nN] ]]; then
      echo "Installation halted."
      sleep inf
    fi
  done
  create_partitions
}

sensible_rootsize() {
  local pvrootsize homesize swapsize vgname label_home label_swap max_swapsize
  max_swapsize=$(get_ram_mb) || return
  (( max_swapsize += 2048 ))
  vgname=$(get_config .storage.plain_lvm.vgname) || return
  label_home=$(get_config .storage.plain_lvm.partition.home) || return
  label_swap=$(get_config .storage.plain_lvm.partition.swap) || return
  [[ -e /dev/mapper/$vgname-$label_home ]] || return
  pvrootsize=$(get_pvrootsize)
  homesize=$(lvs --units b --reportformat json_std | jq -r ".report[0].lv[]|select(.lv_name==\"$label_home\").lv_size" | sed -E 's/^(.*)B$/\1/')
  if [[ -e /dev/mapper/$vgname-$label_swap ]]; then
    swapsize=$(lvs --units b --reportformat json_std | jq -r ".report[0].lv[]|select(.lv_name==\"$label_swap\").lv_size" | sed -E 's/^(.*)B$/\1/')
    (( swapsize /= ( 1024 * 1024 ) ))
  else
    (( swapsize = max_swapsize ))
  fi
  (( homesize /= ( 1024 * 1024 ) ))
  (( rootsize = 65536 ))
  while (( homesize + rootsize + swapsize + 64 > pvrootsize )); do
    (( rootsize -= 1024 ))
  done
  (( rootsize >= 8192 )) || return
  echo $rootsize
}

preserve_home_tasks() {
  local vgname efisys label_home label_root label_efi label_swap swapsize rootsize acc="[]"
  vgname=$(get_config .storage.plain_lvm.vgname) || return
  label_home=$(get_config .storage.plain_lvm.partition.home) || return
  label_root=$(get_config .storage.plain_lvm.partition.root) || return
  label_efi=$(get_config .storage.plain_lvm.partition.efi) || return
  label_swap=$(get_config .storage.plain_lvm.partition.swap) || return
  efisys=$(blkid --label $label_efi) || return
  [[ -e /dev/mapper/$vgname-$label_home ]] || return
  acc=$(jm "$acc" task=preserve dev=/dev/mapper/$vgname-$label_home t=ext4 label=$vgname-$label_home)
  acc=$(jm "$acc" task=wipe dev=$efisys t=efi label=$label_efi)
  if [[ -e /dev/mapper/$vgname-$label_root ]]; then
    acc=$(jm "$acc" task=wipe dev=/dev/mapper/$vgname-$label_root t=ext4 label=$vgname-$label_root)
  else
    rootsize=$(sensible_rootsize) || return
    acc=$(jm "$acc" task=create size=$rootsize t=ext4 vgname=$vgname)
  fi
  if [[ -e /dev/mapper/$vgname-$label_swap ]]; then
    acc=$(jm "$acc" task=preserve dev=/dev/mapper/$vgname-$label_swap t=swap)
  else
    swapsize=$(get_ram_mb) || return
    (( swapsize += 2048 ))
    acc=$(jm "$acc" task=create size=$swapsize t=swap vgname=$vgname)
  fi
  jq -cM ".[]" <<< "$acc"
}

run_task_preserve() {
  local label dev t
  label=$(jq -r ".label | select(. != null)" <<< "$1")
  [[ $label ]] || return 0
  dev=$(jq -r ".dev | select(. != null)" <<< "$1")
  t=$(jq -r ".t | select(. != null)" <<< "$1")
  if [[ $t = "ext4" && $(e2label $dev) != "$label" ]]; then
    e2label $dev $label || return
  fi
}

run_task_wipe() {
  local label dev t
  label=$(jq -r ".label | select(. != null)" <<< "$1")
  [[ $label ]] || return
  dev=$(jq -r ".dev | select(. != null)" <<< "$1")
  t=$(jq -r ".t | select(. != null)" <<< "$1")
  case $t in
    efi)
      mkfs.vfat -n $label -F 32 $dev || return
      ;;
    ext4)
      mkfs.ext4 -q -L $label $dev <<< y || return
      ;;
    *)
      echo "unknown type: $1"
      return 1
      ;;
  esac
}

run_task_create() {
  local label dev t size vgname
  label=$(jq -r ".label | select(. != null)" <<< "$1")
  dev=$(jq -r ".dev | select(. != null)" <<< "$1")
  t=$(jq -r ".t | select(. != null)" <<< "$1")
  size=$(jq -r ".size | select(. != null)" <<< "$1")
  vgname=$(jq -r ".vgname | select(. != null)" <<< "$1")
  [[ $label ]] || return
  [[ $size ]] || return
  [[ $vgname ]] || return
  lvcreate --size ${size}M --name $label $vgname || return
  if [[ $t = "ext4" ]]; then
    mkfs.ext4 -q -L $label $dev <<< y || return
  fi
}

run_task() {
  echo "Running task: $1"
  local task
  task=$(jq -r .task <<< "$1")
  case $task in
    preserve)
      run_task_preserve "$1"
      return
      ;;
    wipe)
      run_task_wipe "$1"
      return
      ;;
    create)
      run_task_create "$1"
      return
      ;;
    *)
      echo "unknown task: $1"
      return 1
      ;;
  esac
}

preserve_home() {
  local m n tasks
  while :; do
    tasks="$(preserve_home_tasks)" || return
    echo "Partitioning tasks:"
    (( n = 1 ))
    while read -r m; do
      echo "$n. $m"
      (( n++ ))
    done <<< "$tasks"
    read -rp "OK to run these tasks? [y/N] "
    if [[ $REPLY =~ [yY] ]]; then
      break
    fi
  done
  while read -r m; do
    run_task "$m" || return
  done <<< "$tasks"
}

prepare_partitions() {
  local dev label_home pv_found vgname REPLY
  label_home=$(get_config .storage.plain_lvm.partition.home) || return
  vgname=$(get_config .storage.plain_lvm.vgname) || return
  for dev in $(lsblk -n --filter 'FSTYPE == "LVM2_member"' -o PATH); do
    if pvs --devices $dev --reportformat json_std | jq -e ".report[].pv[]| select (.vg_name == \"$vgname\")" > /dev/null; then
      vgchange --devices $dev -ay $vgname || return
      break
    fi
  done
  if [[ ! -e /dev/mapper/$vgname-$label_home ]]; then
    echo "No such partition: /dev/mapper/$vgname-$label_home"
    wipe
    return
  fi
  while :; do
    read -rp "Preserve data on /dev/mapper/$vgname-$label_home? [Y/n] "
    if [[ -z $REPLY || $REPLY =~ [yY] ]]; then
      preserve_home
      return
    else
      wipe
      return
    fi
  done
}

return 2> /dev/null || {
  prepare_partitions
}
