#!/bin/bash
#
# This runs very early.
# Its job is to make sure that the partitions named in the profile config exist,
# are formatted and labeled, but not mounted yet.

[[ -v installbase ]] || source /var/tmp/install/common.sh

get_pvrootsize() {
  local disksize efisize=2044
  disksize=$(get_disksize)
  echo $(( disksize - efisize - 32 ))
}

print_parted_commands() {
  local efisize=2044 pos=4 pvrootsize
  pvrootsize=$(get_pvrootsize)
  echo "mklabel gpt"
  echo "mkpart EFISYS fat32 ${pos}MiB $(( pos + efisize ))MiB"
  (( pos += efisize ))
  echo "set 1 esp on"
  echo "mkpart pvroot ext4 ${pos}MiB $(( pos + pvrootsize ))MiB"
  (( pos += pvrootsize ))
}

clean_pv() {
  local disk kname dev
  disk=$(get_disk) || return
  kname=$(lsblk -n --filter "PATH == \"$disk\"" -o KNAME)
  vgname=$(get_config .storage.plain_lvm.vgname)
  for dev in $(lsblk -n --filter "FSTYPE == \"LVM2_member\" && PKNAME == \"$kname\"" -o PATH); do
    if pvs --devices $dev --reportformat json_std | jq -e ".report[].pv[]| select (.vg_name == \"$vgname\")" > /dev/null; then
      vgchange --devices $dev -an || return
      pvremove -y $dev || return
      break
    fi
  done
}

create_basic_partitions() {
  local disk
  disk=$(get_disk) || return
  parted --script --align optimal $disk -- $(print_parted_commands) || return 
  sleep 5
}

create_vg() {
  local vgname pvroot
  vgname=$(get_config .storage.plain_lvm.vgname) || return
  pvroot=$(by_partlabel pvroot) || return
  pvcreate $pvroot || return
  vgcreate $vgname $pvroot || return
}

create_partitions_tasks() {
  local vgname pvrootsize rootsize homesize swapsize label_home label_root label_efi label_swap max_swapsize acc="[]"
  vgname=$(get_config .storage.plain_lvm.vgname) || return
  swapsize=$(get_ram_mb) || return
  (( swapsize += 2048 ))
  pvrootsize=$(get_pvrootsize)
  label_home=$(get_config .storage.plain_lvm.partition.home) || return
  label_root=$(get_config .storage.plain_lvm.partition.root) || return
  label_swap=$(get_config .storage.plain_lvm.partition.swap) || return
  label_efi=$(get_config .storage.plain_lvm.partition.efi) || return
  (( rootsize = 32768 ))
  (( homesize = ( pvrootsize * 4 ) / 5 ))
  while (( homesize + swapsize + rootsize + 64 > pvrootsize )); do
    (( homesize -= 16 ))
    (( rootsize > 9216 && ( rootsize -= 16 ) ))
  done
  if (( homesize < 16384 )); then
    (( homesize += swapsize ))
    (( swapsize = 0 ))
  fi
  (( homesize >= 1024 )) || return
  acc=$(jm "$acc" task=wipe dev=$(by_partlabel EFISYS) t=efi label=$label_efi)
  acc=$(jm "$acc" task=create size=$rootsize t=ext4 vgname=$vgname name=$label_root)
  acc=$(jm "$acc" task=create size=$homesize t=ext4 vgname=$vgname name=$label_home)
  acc=$(jm "$acc" task=create size=$swapsize t=swap vgname=$vgname name=$label_swap)
  jq -cM ".[]" <<< "$acc"
}

wipe() {
  local REPLY
  while :; do
    read -rp "Erase all data on $(get_disk)? [y/N] "
    if [[ $REPLY =~ [yY] ]]; then
      break
    elif [[ $REPLY =~ [nN] ]]; then
      echo "Installation halted."
      sleep inf
    fi
  done
  clean_pv || return
  create_basic_partitions || return
  create_vg || return
  run_storage_tasks "$(create_partitions_tasks)"
}

sensible_sizes() {
  local pvrootsize homesize swapsize vgname label_home
  swapsize=$(get_ram_mb) || return
  (( swapsize += 2048 ))
  vgname=$(get_config .storage.plain_lvm.vgname) || return
  label_home=$(get_config .storage.plain_lvm.partition.home) || return
  [[ -e /dev/mapper/$vgname-$label_home ]] || return
  pvrootsize=$(get_pvrootsize)
  homesize=$(lvs $vgname --units b --reportformat json_std | jq -r ".report[0].lv[]|select(.lv_name==\"$label_home\").lv_size" | sed -E 's/^(.*)B$/\1/')
  (( homesize /= ( 1024 * 1024 ) ))
  (( rootsize = 65536 ))
  while (( homesize + rootsize + swapsize + 64 > pvrootsize )); do
    (( rootsize -= 1024 ))
  done
  if (( rootsize < 16384 )); then
    (( rootsize += swapsize ))
    (( swapsize = 0 ))
  fi
  (( rootsize >= 8192 )) || return
  jq -cM -n "{root:$rootsize,swap:$swapsize,home:$homesize}"
}

preserve_home_tasks() {
  local vgname efisys label_home label_root label_efi label_swap swapsize rootsize sizes acc="[]"
  vgname=$(get_config .storage.plain_lvm.vgname) || return
  label_home=$(get_config .storage.plain_lvm.partition.home) || return
  label_root=$(get_config .storage.plain_lvm.partition.root) || return
  label_efi=$(get_config .storage.plain_lvm.partition.efi) || return
  label_swap=$(get_config .storage.plain_lvm.partition.swap) || return
  efisys=$(blkid --label $label_efi) || return
  [[ -e /dev/mapper/$vgname-$label_home ]] || return
  sizes=$(sensible_sizes) || return
  rootsize=$(jq -r ".root | select(. != null)" <<< "$sizes")
  swapsize=$(jq -r ".swap | select(. != null)" <<< "$sizes")
  acc=$(jm "$acc" task=preserve dev=/dev/mapper/$vgname-$label_home t=ext4 label=$vgname-$label_home)
  acc=$(jm "$acc" task=wipe dev=$efisys t=efi label=$label_efi)
  if [[ -e /dev/mapper/$vgname-$label_root ]]; then
    acc=$(jm "$acc" task=wipe dev=/dev/mapper/$vgname-$label_root t=ext4 label=$vgname-$label_root)
  else
    acc=$(jm "$acc" task=create size=$rootsize t=ext4 vgname=$vgname name=$label_root)
  fi
  acc=$(jm "$acc" task=drop vgname=$vgname name=$label_swap)
  if (( swapsize > 0 )); then
    if [[ -e /dev/mapper/$vgname-$label_swap ]]; then
      acc=$(jm "$acc" task=preserve t=swap dev=/dev/mapper/$vgname-$label_swap)
    else
      acc=$(jm "$acc" task=create size=$swapsize t=swap vgname=$vgname)
    fi
  fi
  jq -cM ".[]" <<< "$acc"
}

prepare_partitions() {
  local dev disk label_home vgname kname REPLY
  label_home=$(get_config .storage.plain_lvm.partition.home) || return
  disk=$(get_disk) || return
  kname=$(lsblk -n --filter "PATH == \"$disk\"" -o KNAME)
  vgname=$(get_config .storage.plain_lvm.vgname) || return
  for dev in $(lsblk -n --filter "FSTYPE == \"LVM2_member\" && PKNAME == \"$kname\"" -o PATH); do
    if pvs --devices $dev --reportformat json_std | jq -e ".report[].pv[]| select (.vg_name == \"$vgname\")" > /dev/null; then
      vgchange --devices $dev -ay $vgname || return
      break
    fi
  done
  if [[ ! -e /dev/mapper/$vgname-$label_home ]]; then
    echo "No such partition: /dev/mapper/$vgname-$label_home"
    wipe
    return
  fi
  while :; do
    read -rp "Preserve data on /dev/mapper/$vgname-$label_home? [Y/n] "
    if [[ -z $REPLY || $REPLY =~ [yY] ]]; then
      run_storage_tasks "$(preserve_home_tasks)"
      return
    else
      wipe
      return
    fi
  done
}

return 2> /dev/null || {
  prepare_partitions
}
