#!/bin/bash
#
# This runs very early.
# Its job is to make sure that the partitions named in the profile config exist,
# are formatted and labeled, but not mounted yet.

[[ -v installbase ]] || source /var/tmp/install/common.sh

get_pvrootsize() {
  local disksize efisize=2044
  disksize=$(get_disksize)
  echo $(( disksize - efisize - 32 ))
}

print_parted_commands() {
  local efisize=2044 pos=4 pvrootsize pvname
  pvrootsize=$(get_pvrootsize)
  pvname=$(get_config .storage.plain_lvm.pvname) || return
  echo "mklabel gpt"
  echo "mkpart EFISYS fat32 ${pos}MiB $(( pos + efisize ))MiB"
  (( pos += efisize ))
  echo "set 1 esp on"
  echo "mkpart $pvname ext4 ${pos}MiB $(( pos + pvrootsize ))MiB"
  (( pos += pvrootsize ))
}

wipe() {
  local disk part pvname vgname pvroot pvrootsize rootsize homesize label_home label_root label_efi volgs
  pvrootsize=$(get_pvrootsize)
  vgchange -an
  pvname=$(get_config .storage.plain_lvm.pvname) || return
  vgname=$(get_config .storage.plain_lvm.vgname) || return
  label_home=$(get_config .storage.plain_lvm.partition.home) || return
  label_root=$(get_config .storage.plain_lvm.partition.root) || return
  label_efi=$(get_config .storage.plain_lvm.partition.efi) || return
  disk=$(get_disk) || return
  parted --script --align optimal $disk -- $(print_parted_commands) || return 
  mkfs.vfat -n $label_efi -F 32 $(by_partlabel EFISYS) || return
  pvroot=$(by_partlabel $pvname) || return
  volgs=$(vgs --noheadings | sed -E 's/^\s*\b(\S+)\b.*/\1/')
  if [[ $volgs = "$vgname" ]]; then
    vgremove -f $vgname
  fi
  pvcreate $pvroot || return
  vgcreate $vgname $pvroot || return
  (( rootsize = pvrootsize / 2 ))
  (( rootsize > 65536 && ( rootsize = 65536 ) ))
  (( rootsize < 8192 && ( rootsize = 8192 ) ))
  (( homesize = pvrootsize - rootsize - 32 ))
  (( homesize > 65536 && ( homesize = 65536 ) ))
  (( homesize >= 1024 )) || return
  lvcreate -L ${rootsize}M -n $label_root $vgname || return
  lvcreate -L ${homesize}M -n $label_home $vgname || return
  mkfs.ext4 -q -L $vgname-$label_root /dev/mapper/$vgname-$label_root <<< y || return
  mkfs.ext4 -q -L $vgname-$label_home /dev/mapper/$vgname-$label_home <<< y || return
}

only_format_root() {
  local vgname efisys label_home label_root label_efi
  vgname=$(get_config .storage.plain_lvm.vgname) || return
  label_home=$(get_config .storage.plain_lvm.partition.home) || return
  label_root=$(get_config .storage.plain_lvm.partition.root) || return
  label_efi=$(get_config .storage.plain_lvm.partition.efi) || return
  efisys=$(blkid --label $label_efi) || return
  linuxroot=$(blkid --label $vgname-$label_root) || return
  mkfs.ext4 -q -L $vgname-$label_root $linuxroot <<< y || return
  mkfs.vfat -n $label_efi -F 32 $efisys || return
}

prepare_partitions() {
  local label_home REPLY
  vgchange -ay
  label_home=$(get_config .storage.plain_lvm.partition.home) || return
  if blkid --label $label_home &> /dev/null; then
    # todo: ask if wipe desired
    only_format_root
  else
    while true; do
      read -rp "Erase all data on $(get_disk)? [y/N] "
      [[ $REPLY =~ [yY] ]] && break
      [[ $REPLY =~ [nN] ]] && { echo "Installation halted." ; sleep inf ; }
    done
    wipe
  fi
}

return 2> /dev/null || {
  prepare_partitions
}
